GCC = g++
FLAGS = -g

default: frequency integers

frequency: frequency.cpp
	$(GCC) $(FLAGS) frequency.cpp -o frequency

integers: integers.cpp
	$(GCC) $(FLAGS) integers.cpp -o integers

clean:
	rm -f frequency integers
