CXX = g++
FLAGS = -ggdb
default: ex1 ex2 ex3 ex4 ex5
ex1: ex1.cpp
	$(CXX) $(FLAGS) ex1.cpp -o ex1 
ex2: ex2.cpp
	$(CXX) $(FLAGS) ex2.cpp -o ex2
ex3: ex3.cpp
	$(CXX) $(FLAGS) ex3.cpp -o ex3 
ex4: ex4.cpp
	$(CXX) $(FLAGS) ex4.cpp -o ex4 
ex5: ex5.cpp
	$(CXX) $(FLAGS) ex5.cpp -o ex5 

